### ISSUE TITLE
Utility Umbrella Mechanics

### ISSUE THREAD

**Issue by KrisXV** [smogon/pokemon-showdown#6121]
- [x] Does Utility Umbrella allow the holder to use Water moves in Desolate Land/Fire moves in Primordial Sea?
- [x] Does Utility Umbrella allow freezing to happen in the sun?
- [x] How does Solar Power interact with Utility Umbrella?
- [x] Does Utility Umbrella nullify the 50% Sp. Def boost to Rock types in Sandstorm?
- [x] Is Castform holding Utility Umbrella prevented from transforming into Castform-Sunny/Rainy in the respective weathers (this one will have to be an assumed mechanic for the time being since Castform isn't in Sword/Shield)?
- [x] Are weather-dependent accuracy moves (Thunder, Hurricane) still able to miss when used against a Pokemon holding Utility Umbrella (Hurricane Gyarados vs. Utility Umbrella Pokemon)?
- [x] Is a statused Pokemon with Hydration holding Utility Umbrella cured in the rain or not?
- [x] Does Growth still boost the user's Atk and Sp. Atk 2 stages in the sun with Utility Umbrella equipped?
- [x] Does Utility Umbrella prevent the holder from using Aurora Veil in Hail?
- [x] What happens if you use Trick to give Cherrim a Utility Umbrella when Sun is active?

Feel free to add more/post answers to listed mechanics questions (with proof)

**Comment by KrisXV** [comment]
> Does Utility Umbrella allow the holder to use Water moves in Desolate Land/Fire moves in Primordial Sea?

no

> Does Utility Umbrella allow freezing to happen in the sun?

yes

> How does Solar Power interact with Utility Umbrella?

As expected; the holder does not lose HP and its Sp. Atk is not boosted.

> Does Utility Umbrella nullify the 50% Sp. Def boost to Rock types in Sandstorm?

no

> Is Castform holding Utility Umbrella prevented from transforming into Castform-Sunny/Rainy in the respective weathers (this one will have to be an assumed mechanic for the time being since Castform isn't in Sword/Shield)?

I've implemented it with Flower Gift as a basis; if the weather is rain/sun and the holder is a Castform, it will not transform.

> Are weather-dependent accuracy moves (Thunder, Hurricane) still able to miss when used against a Pokemon holding Utility Umbrella (Hurricane Gyarados vs. Utility Umbrella Pokemon)?

yes!

> Is a statused Pokemon with Hydration holding Utility Umbrella cured in the rain or not?

no, it is not cured.

> Does Growth still boost the user's Atk and Sp. Atk 2 stages in the sun with Utility Umbrella equipped?

no

> Does Utility Umbrella prevent the holder from using Aurora Veil in Hail?

credits to @QuiteQuiet for this question
no

> What happens if you use Trick to give Cherrim a Utility Umbrella when Sun is active?

credits to @urkerab for this question
If Utility Umbrella is given to Cherrim-Sunshine via Trick/Switcheroo, it reverts to its base forme. Similarly, if Sun is up and a Utility Umbrella is taken away from Cherrim, it will transform into Cherrim-Sunshine.

thank you to @Lusamine for testing all of these! (https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/page-32#post-8308588)

**Comment by QuiteQuiet** [comment]
Does Weather Ball still change type/base power when the user is holding an Utility Umbrella (or the target..?)?
Maybe implemented, but does Solar Beam do full damage in Rain/Sandstorm with an Utility Umbrella?

**Comment by KrisXV** [comment]
Handled in #6120 #6127 and #6180
